CREATE TABLE `Board` (
	`bId` INT(50) auto_increment NOT NULL,
	`bName` TINYTEXT NOT NULL,
	`bTitle` LONGTEXT NOT NULL,
	`bContent` LONGTEXT NOT NULL,
	`bDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`bHit` INT(50) NOT NULL,
	`bGroup` INT(50) NOT NULL,
	`bStep` INT(50) NOT NULL,
	`bIndent` INT(50) NOT NULL,
	
	PRIMARY KEY (`bId`)
)ENGINE=MyISAM AUTO_INCREMENT=1203 DEFAULT CHARSET=utf8


CREATE TABLE `comment` (
	`c_idx` INT(11) NOT NULL AUTO_INCREMENT,
	`b_comant` INT(11) NOT NULL,
	`content` VARCHAR(30) NOT NULL,
	`date` DATETIME NOT NULL,
	`b_idx` INT(11) NOT NULL,
	PRIMARY KEY (`c_idx`)
)ENGINE=MyISAM AUTO_INCREMENT=1203 DEFAULT CHARSET=utf8



CREATE TABLE `b_file` (
	`f_idx` INT(11) NOT NULL,
	`file_name` VARCHAR(20) NULL DEFAULT NULL,
	`file_type` VARCHAR(20) NULL DEFAULT NULL,
	`file_path` VARCHAR(30) NOT NULL,
	`b_idx` INT(11) NOT NULL,
	PRIMARY KEY (`f_idx`)
)ENGINE=MyISAM AUTO_INCREMENT=1203 DEFAULT CHARSET=utf8




CREATE TABLE `tbl_member` (
	'userId' INT(50) NOT NULL AUTO_INCREMENT,
	'userPw' INT(50) NOT NULL,
	'userName' INT(50) NOT NULL,
	'userRegdate' DATETIME NOT NULL,
	'userEmail' INT(50) NULL,
	PRIMARY KEY ('userId')
)ENGINE=MyISAM AUTO_INCREMENT=1203 DEFAULT CHARSET=utf8



COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;
